# Generated by Django 4.1.3 on 2022-12-06 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('domain_id', models.IntegerField()),
                ('main_category', models.CharField(blank=True, max_length=16)),
                ('sub_category', models.CharField(blank=True, max_length=16)),
                ('writed_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('content', models.TextField()),
                ('url', models.CharField(blank=True, max_length=255)),
                ('photo_url', models.TextField(blank=True)),
                ('writer', models.CharField(blank=True, max_length=16)),
                ('stickers', models.TextField(blank=True)),
                ('press', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('c_writed_at', models.DateTimeField(blank=True, null=True)),
                ('c_content', models.TextField(blank=True)),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
